=pod
=head1 Online resources for PiFlash

This is a list of online resources for PiFlash

=head2 Where to download Raspberry Pi bootable images

The first place to look for Raspberry Pi bootable images is usually the Raspberry Pi Foundation's download page.
L<https://www.raspberrypi.org/downloads/> . But they stopped adding new sources at some point. There are more.

=over

=item Fedora Linux downloads for ARM processors L<https://arm.fedoraproject.org/>

=item FreeBSD downloads L<https://www.freebsd.org/where.html> includes Raspberry Pi SD card images

=item FreedomBox L<https://freedombox.org/download/stable/> personal server project of Debian Linux

=back
